name: meme_player
description: A cross-platform media player application for videos and music.

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: any
  video_player: any
  chewie: any
  file_picker:  any
  path_provider: any
  path: any
  subtitle: any
  provider: any
  shared_preferences: any
  window_manager: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/