name: meme_player
description: A cross-platform media player application for videos and music.

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  video_player: ^2.7.0
  chewie: ^1.7.0
  file_picker: ^5.3.2
  path_provider: ^2.0.15
  path: ^1.8.3
  subtitle: ^0.1.0
  provider: ^6.0.5
  shared_preferences: ^2.2.0
  window_manager: ^0.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/